### ISSUE TITLE
What happened to Ashley Kleynhans' Docker images?

### ISSUE THREAD

**Issue by ddpasa** [kodxana/Awesome-RunPod#23]
I was a big fan of @ashleykleynhans docker images, especially ashleykza/runpod-base. What happened to them? Would you allow us to fork the repos so we can keep developing them?

**Comment by ddpasa** [comment]
Thats a shame!  Your work was really good, and it's bad Runpod treated you like that.  Any recommendations on alternative platforms to Runpod?

**Comment by ashleykleynhans** [comment]
You can try vast.ai

**Comment by kodxana** [comment]
From what I heard it was some toxic behaviour between you and Polar. that got you banned and then ban evasion using alt accounts
Cant say much as I do not know whole context of the situation.

**Comment by ashleykleynhans** [comment]
> From what I heard it was some toxic behaviour between you and Polar. that got you banned and then ban evasion using alt accounts Cant say much as I do not know whole context of the situation.

RunPod Discord was a better place before Polar/haris/whatever joined and made it go downhill.  He is supposed to be the "Community Manager" but is probably the most inactive person on the entire RunPod Discord, and takes like 3 days to respond to issues instead of addressing them immediately.   If a valued community member says something that is out of line etc, its simple enough for a moderator to delete it and asked them to refrain from doing so in future, banning is totally uncalled for when people contribute so much hard work to the community for extremely minimal reward.

**Comment by ddpasa** [comment]
> From what I heard it was some toxic behaviour between you and Polar. that got you banned and then ban evasion using alt accounts Cant say much as I do not know whole context of the situation.

@kodxana I don't use discord and I don't know about the dynamics there.  But the only reason I used Runpod was because Ashley's images made Runpod easy to use.  If that open-source ecosystem does not exist, then there is no reason for me to use Runpod.  I'm giving vast.ai a try now, it looks very nice.
